server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /data/ {
        alias /srv/airpre-data/;
        default_type application/json;
        add_header Cache-Control "no-store";
    }
}
